
spring: 
  application:
    name: Discord Bot
  main:
    web-application-type: none

discord:
  oauth2-url: ""
  token: ""
  status: 
    name: "Under Development"
    status: online
    type: default
  users:
    - alias: Wipu 
      snowflake-id: ""
      role: owner
    - alias: P'Ake
      snowflake-id: ""
      role: admin
    - alias: P'Ake
      snowflake-id: ""
      role: admin      
  audio-folder: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio"
