
spring: 
  profiles:
    active:
     - cloud
  application:
    name: Discord-Bot
  main:
    web-application-type: none

discord:
  oauth2-url: ${OAUTH2_URL}
  token: ${TOKEN}
  status: 
    name: ${STATUS:-Under Development}
    status: online
    type: default
  users:
    - alias: Wipu 
      snowflake-id: "743921134944124989"
      role: owner
    - alias: P'Ake
      snowflake-id: "212266082344370177"
      role: admin
    - alias: Hulk
      snowflake-id: "285029601271480320"
      role: admin
  audios:
    - name: alert-error-detected
      path: "${AUDIO_DIR}/audio/en/en-alert-error-detected.mp3"
    - name: alert-out-of-disk-space-detected
      path: "${AUDIO_DIR}/audio/en/en-alert-out-of-disk-space-detected.mp3"
    - name: alert-out-of-memory-detected
      path: "${AUDIO_DIR}/audio/en/en-alert-out-of-memory-detected.mp3"
    - name: alert-warning-detected
      path: "${AUDIO_DIR}/audio/en/en-alert-warning-detected.mp3"
    - name: before-time-to-expedition
      path: "${AUDIO_DIR}/audio/th/th-before-time-to-expedition.mp3"
    - name: before-time-to-login-web
      path: "${AUDIO_DIR}/audio/th/th-before-time-to-login-web.mp3"
    - name: before-time-to-new-abyss
      path: "${AUDIO_DIR}/audio/th/th-before-time-to-new-abyss.mp3"
    - name: before-time-to-new-gacha
      path: "${AUDIO_DIR}/audio/th/th-before-time-to-new-gacha.mp3"
    - name: before-time-to-route-artifact
      path: "${AUDIO_DIR}/audio/th/th-before-time-to-route-artifact.mp3"
    - name: before-time-to-transform-junk
      path: "${AUDIO_DIR}/audio/th/th-before-time-to-transform-junk.mp3"
    - name: before-time-to-unknown
      path: "${AUDIO_DIR}/audio/th/th-before-time-to-unknown.mp3"
    - name: dont-forget-weekly-boss
      path: "${AUDIO_DIR}/audio/th/th-dont-forget-weekly-boss.mp3"
    - name: member-online
      path: "${AUDIO_DIR}/audio/th/th-member-online.mp3"
    - name: time-to-dig-mineral
      path: "${AUDIO_DIR}/audio/th/th-time-to-dig-mineral.mp3"
    - name: time-to-expedition
      path: "${AUDIO_DIR}/audio/th/th-time-to-expedition.mp3"
    - name: time-to-login-web
      path: "${AUDIO_DIR}/audio/th/th-time-to-login-web.mp3"
    - name: time-to-new-abyss
      path: "${AUDIO_DIR}/audio/th/th-time-to-new-abyss.mp3"
    - name: time-to-new-event
      path: "${AUDIO_DIR}/audio/th/th-time-to-new-event.mp3"
    - name: time-to-new-gacha
      path: "${AUDIO_DIR}/audio/th/th-time-to-new-gacha.mp3"
    - name: time-to-route-artifact
      path: "${AUDIO_DIR}/audio/th/th-time-to-route-artifact.mp3"
    - name: time-to-transform-junk
      path: "${AUDIO_DIR}/audio/th/th-time-to-transform-junk.mp3"
