
spring: 
  application:
    name: Discord-Bot
  main:
    web-application-type: none

discord:
  oauth2-url: ${OAUTH2_URL}
  token: ${TOKEN}
  status: 
    name: ${STATUS}
    status: online
    type: default
  users:
    - alias: Wipu 
      snowflake-id: "743921134944124989"
      role: owner
    - alias: P'Ake
      snowflake-id: "212266082344370177"
      role: admin
    - alias: Hulk
      snowflake-id: "285029601271480320"
      role: admin
  audio-folder: ${AUDIO_DIR}
