
spring: 
  application:
    name: Discord Bot
  main:
    web-application-type: none

discord:
  oauth2-url: ""
  token: ""
  status: 
    name: "Under Development"
    status: online
    type: default
  users:
    - alias: Wipu 
      snowflake-id: ""
      role: owner
    - alias: P'Ake
      snowflake-id: ""
      role: admin
    - alias: P'Ake
      snowflake-id: ""
      role: admin      
  audios:
    - name: alert-error-detected
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/en/en-alert-error-detected.mp3"
    - name: alert-out-of-disk-space-detected
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/en/en-alert-out-of-disk-space-detected.mp3"
    - name: alert-out-of-memory-detected
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/en/en-alert-out-of-memory-detected.mp3"
    - name: alert-warning-detected
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/en/en-alert-warning-detected.mp3"
    - name: before-time-to-expedition
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-before-time-to-expedition.mp3"
    - name: before-time-to-login-web
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-before-time-to-login-web.mp3"
    - name: before-time-to-new-abyss
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-before-time-to-new-abyss.mp3"
    - name: before-time-to-new-gacha
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-before-time-to-new-gacha.mp3"
    - name: before-time-to-route-artifact
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-before-time-to-route-artifact.mp3"
    - name: before-time-to-transform-junk
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-before-time-to-transform-junk.mp3"
    - name: before-time-to-unknown
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-before-time-to-unknown.mp3"
    - name: dont-forget-weekly-boss
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-dont-forget-weekly-boss.mp3"
    - name: member-online
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-member-online.mp3"
    - name: time-to-dig-mineral
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-dig-mineral.mp3"
    - name: time-to-expedition
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-expedition.mp3"
    - name: time-to-login-web
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-login-web.mp3"
    - name: time-to-new-abyss
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-new-abyss.mp3"
    - name: time-to-new-event
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-new-event.mp3"
    - name: time-to-new-gacha
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-new-gacha.mp3"
    - name: time-to-route-artifact
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-route-artifact.mp3"
    - name: time-to-transform-junk
      path: "C:/Users/PC/Documents/workspace-spring-tool-suite-4/discord-bot/src/main/resources/audio/th/th-time-to-transform-junk.mp3"
