
spring: 
  application:
    name: Discord Bot
  main:
    web-application-type: none

discord:
  oauth2-url: ""
  token: ""
  status: 
    name: "Under Development"
    status: online
    type: default
  users:
    - alias: Wipu 
      snowflake-id: ""
      role: owner
    - alias: Admin
      snowflake-id: ""
      role: admin
  audio-folder: ""

repository:
  directory-path: ""