start-state: &startState start
error-state: &errorEvent error 

transition: 
  - from-state: *startState
    to-state: &bot bot
    on-strings: 
      - "<@!814147231568887828>"
    on-events: 
      - type: equals-ignore-case
        value: bot
      - type: equals-ignore-case
        value: paimon
 
##### log out
  - from-state: *bot
    to-state: do.log-out
    on-strings: 
      - shutdown 
      - log out
    call-actions: 
      - do.log-out

##### join current voice channel
  - from-state: *bot
    to-state: join.author.voiceChannel
    on-strings: 
      - come here
    call-actions:
      - get.authorVoiceChannel     
      - do.join-authorVoiceChannel
    
  - from-state: *bot
    to-state: &join join.channel
    on-strings: 
      - join 
      - enter
    
  - from-state: *join
    to-state: join.author.voiceChannel
    on-strings: 
      - here
      - me
      - current channel
      - this channel
    call-actions:
      - get.authorVoiceChannel     
      - do.join-authorVoiceChannel

##### leave voice channel
  - from-state: *bot
    to-state: &leave leave.channel
    on-strings: 
      - leave
      - get out
    call-actions: 
      - do.leave-voiceChannel
      
#### tell someone

#### schedule alert

#### query alert






